const Discord = require('discord.js');
const fs = require('fs');

function display_names(client) {

    // Makes an easy to parse JSON object using our strike file
    var strike_data = require('../user_strikes_data.json');

    // Get a list of the names
    var usernames = []
    for (key in strike_data) {
        usernames.push(strike_data[key].name);
    }

    // inside a command, event listener, etc.
    const exampleEmbed = new Discord.MessageEmbed() 
        .setColor('#9d03fc')
        .setAuthor('Display names? Well, here you go:', 'https://api-assets.clashofclans.com/badges/512/xXro3-How4UeBogChbE8uiFRM8iCM1jAQEKbGKKGhmU.png')
        .addFields(
            { name: "War Farmers: ", value: usernames }
        )
        .setTimestamp()
        .setFooter('Generated by Chief Bot Alpha', 'https://api-assets.clashofclans.com/badges/512/xXro3-How4UeBogChbE8uiFRM8iCM1jAQEKbGKKGhmU.png');

    const channel = client.channels.cache.get('717213839267201061');
    channel.send(exampleEmbed);

    //msg.reply(usernames);
}

function display_strikes(client) {

    // Makes an easy to parse JSON object using our strike file
    var strike_data = require('../user_strikes_data.json');
    const channel = client.channels.cache.get('717213839267201061');

    var embed = []

    // Get a list of the names
    for (key in strike_data) {
        // console.log(strike_data[key].num_strikes)

        // Find a user with a strike
        if (strike_data[key].num_strikes == "1") {        
            
            var reason1 = strike_data[key].reasons[0].reason_1;
            var our_value = ["1. " + reason1]

            embed.push({name: strike_data[key].name, value: our_value});

        }
        else if (strike_data[key].num_strikes == "2") {

            var reason1 = strike_data[key].reasons[0].reason_1;
            var reason2 = strike_data[key].reasons[0].reason_2;
            var our_value = ["1. " + reason1, "2. " + reason2];

            embed.push({name: strike_data[key].name, value: our_value});

        }
        else if (strike_data[key].num_strikes == "3") {

            var reason1 = strike_data[key].reasons[0].reason_1;
            var reason2 = strike_data[key].reasons[0].reason_2;
            var reason3 = strike_data[key].reasons[0].reason_3;
            var our_value = ["1. " + reason1, "2. " + reason2, "3. " + reason3];

            embed.push({name: strike_data[key].name, value: our_value});
        }
    }

    // inside a command, event listener, etc.
    const exampleEmbed = new Discord.MessageEmbed() 
        .setColor('#9d03fc')
        .setAuthor('Here are all the strikes so far: ', 'https://api-assets.clashofclans.com/badges/512/xXro3-How4UeBogChbE8uiFRM8iCM1jAQEKbGKKGhmU.png')
        .addFields(
            embed
        )
        .setTimestamp()
        .setFooter('Generated by Chief Bot Alpha', 'https://api-assets.clashofclans.com/badges/512/xXro3-How4UeBogChbE8uiFRM8iCM1jAQEKbGKKGhmU.png');


        channel.send(exampleEmbed);
}

function display_welcome(client) {

    const channel = client.channels.cache.get('742801891704045639');

    const exampleEmbed = new Discord.MessageEmbed() 
    .setColor('#9d03fc')
    .setAuthor('Congratulations on joining our clan! ', 'https://api-assets.clashofclans.com/badges/512/xXro3-How4UeBogChbE8uiFRM8iCM1jAQEKbGKKGhmU.png')
    .addFields(
        { name: 'Here is what you need to do next:', value: '1. Head over to #verification and read rules.\n2. React to verify.\n3. Head over to #role-select.\n4. React to the clan you are in.\n' },
        { name: 'Optional', value: '5. React to QOTD to be pinged for QOTD. \n6. React to Fun Events to be pinged for fun events. \n7. React to Bot Usage to gete access to bot channels.' }
        
    )
    .setTimestamp()
    .setFooter('Generated by Chief Bot Alpha', 'https://api-assets.clashofclans.com/badges/512/xXro3-How4UeBogChbE8uiFRM8iCM1jAQEKbGKKGhmU.png');

    channel.send(exampleEmbed);
}

/*
  The functions that are exported from this module (meaning they can be used in other files as well)
*/
module.exports = {

    display_names : display_names,
    display_strikes : display_strikes,
    display_welcome : display_welcome

};
