const Discord = require('discord.js');
const fs = require('fs');

function display_names(client) {

    // Makes an easy to parse JSON object using our strike file
    var strike_data = require('../user_strikes_data.json');

    // Get a list of the names
    var usernames = []
    for (key in strike_data) {
        usernames.push(strike_data[key].name);
    }

    // inside a command, event listener, etc.
    const exampleEmbed = new Discord.MessageEmbed() 
        .setColor('#9d03fc')
        .setAuthor('Display names? Well, here you go:', 'https://api-assets.clashofclans.com/badges/512/xXro3-How4UeBogChbE8uiFRM8iCM1jAQEKbGKKGhmU.png')
        .addFields(
            { name: "War Farmers: ", value: usernames }
        )
        .setTimestamp()
        .setFooter('Generated by Chief Bot Alpha', 'https://api-assets.clashofclans.com/badges/512/xXro3-How4UeBogChbE8uiFRM8iCM1jAQEKbGKKGhmU.png');

    const channel = client.channels.cache.get('717213839267201061');
    channel.send(exampleEmbed);

    //msg.reply(usernames);
}

function display_strikes(client) {

    // Makes an easy to parse JSON object using our strike file
    var strike_data = require('../user_strikes_data.json');
    const channel = client.channels.cache.get('717213839267201061');

    var embed = []

    // Get a list of the names
    for (key in strike_data) {
        // console.log(strike_data[key].num_strikes)

        // Find a user with a strike
        if (strike_data[key].num_strikes == "1") {        

            channel.send(strike_data[key].name + " has a strike ");
            
            var reason1 = strike_data[key].reasons[0].reason_1;
            var our_value = ["1. " + reason1]


        }
        else if (strike_data[key].num_strikes == "2") {

            channel.send(strike_data[key].name + " has " + strike_data[key].num_strikes + " strikes ");

            var reason1 = strike_data[key].reasons[0].reason_1;
            var reason2 = strike_data[key].reasons[0].reason_2;
            var our_value = ["1. " + reason1, "2. " + reason2];

            console.log(our_value)

            console.log({name: strike_data[key].name, value: our_value});

        }
        else if (strike_data[key].num_strikes == "3") {

            channel.send(strike_data[key].name + " has " + strike_data[key].num_strikes + " strikes ");

            var reason1 = strike_data[key].reasons[0].reason_1;
            var reason2 = strike_data[key].reasons[0].reason_2;
            var reason3 = strike_data[key].reasons[0].reason_3;
            var our_value = ["1. " + reason1, "2. " + reason2, "3. " + reason3];

            console.log(our_value)

            console.log({name: strike_data[key].name, value: our_value});
        }
    }

    // WHAT OUR EMBED SHOULD LOOK LIKE vvvv

    // var string = ["hello", "this", "is", "a", "test"]

    // var embed = [
    //     { name: "value 1: ", value: "1" }, 
    //     { name: "value 2: ", value: "2" },
    //     { name: "value 3: ", value: string }
    // ]

    // inside a command, event listener, etc.
    const exampleEmbed = new Discord.MessageEmbed() 
        .setColor('#9d03fc')
        .setAuthor('Display names? Well, here you go:', 'https://api-assets.clashofclans.com/badges/512/xXro3-How4UeBogChbE8uiFRM8iCM1jAQEKbGKKGhmU.png')
        .addFields(
            embed
        )
        .setTimestamp()
        .setFooter('Generated by Chief Bot Alpha', 'https://api-assets.clashofclans.com/badges/512/xXro3-How4UeBogChbE8uiFRM8iCM1jAQEKbGKKGhmU.png');

    // const channel = client.channels.cache.get('717213839267201061');
    channel.send(exampleEmbed);

    //msg.reply(usernames);
}

/*
  The functions that are exported from this module (meaning they can be used in other files as well)
*/
module.exports = {

    display_names : display_names,
    display_strikes : display_strikes

};
