/**
 *  Contains the code for all message displays. The goal of this module is to provide functions that allow us to
 *  display various different lists/items to our Discord server in a beautiful visual (by using Discord embeds)
 * 
 *  Relevant functions: 
 *    @display_names()
 *    @display_strikes()
 *    @display_welcome()
 * 
 *  File for bot verion: 1.0
 */

const Discord = require('discord.js');
const fs = require('fs');

/* 
  This function uses a Discord embed to make a visual of all the current players
  in the clan. It uses our strike data file to generate the list of names. 

  Parameters:
     @client: Our Discord server
*/
function display_names(client) {

    // Makes an easy to parse JSON object using our strike file
    var strike_data = require('../user_strikes_data.json');

    // Get a list of the names
    var usernames = []
    for (key in strike_data) {
        if (strike_data[key].active === true) {
            usernames.push(strike_data[key].name + " - " + strike_data[key].id);
        }
    }

    // Alphabetize
    usernames.sort();

    // inside a command, event listener, etc.
    const exampleEmbed = new Discord.MessageEmbed() 
        .setColor('#9d03fc')
        .setAuthor('Display names? Well, here you go:', 'https://api-assets.clashofclans.com/badges/512/xXro3-How4UeBogChbE8uiFRM8iCM1jAQEKbGKKGhmU.png')
        .addFields(
            { name: "War Farmers: ", value: usernames }
        )
        .setTimestamp()
        .setFooter('Generated by Chief Bot Alpha', 'https://api-assets.clashofclans.com/badges/512/xXro3-How4UeBogChbE8uiFRM8iCM1jAQEKbGKKGhmU.png');

    // Our target Discord channel. Note: Actual channel ID leads nowhere :)
    const channel = client.channels.cache.get('717213839267201061');

    // Post our embed in the target channel
    channel.send(exampleEmbed);
}

/* 
  This function uses a Discord embed to make a visual of all the current strikes a player
  in the clan has. It uses our strike data file to generate the list of strikes. 

  Parameters:
     @client: Our Discord server
*/
function display_strikes(client) {

    // Makes an easy to parse JSON object using our strike file
    var strike_data = require('../user_strikes_data.json');

    // Our target Discord channel. Note: Actual channel ID leads nowhere :)
    const channel = client.channels.cache.get('717213839267201061');

    var embed = []
    // Get a list of the names
    for (key in strike_data) {

        // Find a user with a strike
        if (strike_data[key].num_strikes == "1") {        
            
            var reason1 = strike_data[key].reasons[0].reason_1;
            var our_value = ["1. " + reason1]

            embed.push({name: strike_data[key].name, value: our_value});

        }
        else if (strike_data[key].num_strikes == "2") {

            var reason1 = strike_data[key].reasons[0].reason_1;
            var reason2 = strike_data[key].reasons[0].reason_2;
            var our_value = ["1. " + reason1, "2. " + reason2];

            embed.push({name: strike_data[key].name, value: our_value});

        }
        else if (strike_data[key].num_strikes == "3") {

            var reason1 = strike_data[key].reasons[0].reason_1;
            var reason2 = strike_data[key].reasons[0].reason_2;
            var reason3 = strike_data[key].reasons[0].reason_3;
            var our_value = ["1. " + reason1, "2. " + reason2, "3. " + reason3];

            embed.push({name: strike_data[key].name, value: our_value});
        }
    }

    // inside a command, event listener, etc.
    const exampleEmbed = new Discord.MessageEmbed() 
        .setColor('#9d03fc')
        .setAuthor('Here are all the strikes so far: ', 'https://api-assets.clashofclans.com/badges/512/xXro3-How4UeBogChbE8uiFRM8iCM1jAQEKbGKKGhmU.png')
        .addFields(
            embed
        )
        .setTimestamp()
        .setFooter('Generated by Chief Bot Alpha', 'https://api-assets.clashofclans.com/badges/512/xXro3-How4UeBogChbE8uiFRM8iCM1jAQEKbGKKGhmU.png');

    // Post our embed in the target channel     
    channel.send(exampleEmbed);
}

/* 
  This function uses a Discord embed to make an aesthetically pleasing welcome message. That way
  when someone joins the server, they automatically get a message indicating what to do next!

  Parameters:
     @client: Our Discord server
*/
function display_welcome(client) {

    // Our target Discord channel. Note: Actual channel ID leads nowhere :)
    const channel = client.channels.cache.get('742801891704045639');

    const exampleEmbed = new Discord.MessageEmbed() 
    .setColor('#9d03fc')
    .setAuthor('Congratulations on joining our clan! ', 'https://api-assets.clashofclans.com/badges/512/xXro3-How4UeBogChbE8uiFRM8iCM1jAQEKbGKKGhmU.png')
    .addFields(
        { name: 'Here is what you need to do next:', value: '1. Head over to #verification and read rules.\n2. React to verify.\n3. Head over to #role-select.\n4. React to the clan you are in.\n' },
        { name: 'Optional', value: '5. React to QOTD to be pinged for QOTD. \n6. React to Fun Events to be pinged for fun events. \n7. React to Bot Usage to gete access to bot channels.' }
        
    )
    .setTimestamp()
    .setFooter('Generated by Chief Bot Alpha', 'https://api-assets.clashofclans.com/badges/512/xXro3-How4UeBogChbE8uiFRM8iCM1jAQEKbGKKGhmU.png');

    // Post our embed in the target channel
    channel.send(exampleEmbed);
}

/*
  The functions that are exported from this module (meaning they can be used in other files as well)
*/
module.exports = {

    display_names : display_names,
    display_strikes : display_strikes,
    display_welcome : display_welcome
    
};
